site_name: David's Brain Dump
docs_dir: docs-md
site_dir: docs

theme:
  name: material
  logo: images/logo.svg
  font:
    code: Source Sans Pro

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - codehilite:
      linenums: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

plugins:
  - search # necessary for search to work
  - awesome-pages

copyright: "Copyright (C) 2020 David Pham"
