:PROPERTIES:
:ID:       a5ae204f-2b2a-4bbc-8e67-86bfe3f1e350
:ROAM_ALIASES: build-tool cljs
:END:
#+TITLE: shadow-cljs
#+OPTIONS: toc:nil
#+filetags: :cljs:js:webapp:tool:front_end:nginx:clj_toolkit:

* shadow-cljs

** NGINX Configuration for developping locally

Install nginx on your remote server and place this file into your
configuration.

#+BEGIN_SRC conf
  server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    server_name _;

    location / {
      proxy_pass http://localhost:8080/;
      try_files $uri $uri/a 404;
    }

    location /shadow-cljs/ {
      # upgrade to websocket
      proxy_pass http://localhost:9630/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
    }

  }
   #+END_SRC

- Open the ports: `sudo ufw 8080` and `sudo ufw 9630`.
- Connect directly to the ip/domain of the server with the correct ports.

** Inspect

   Inject the correct namespaces with ~:devtools~ preloads in the
   =shadow-cljs.edn= config file.

   #+begin_src clojure
     {:devtools
      {:preloads [shadow.remote.runtime.cljs.browser
                  ;; shadow.remote.runtime.cljs.node ;; for nodejs
                  ]}}
   #+end_src

   Inspect with Clojure and not only ClojureScript

   #+begin_src clojure
     (require '[shadow.cljs.devtools.server :as server])
     (server/start!)
     (tap> :hello)
   #+end_src

** Devcards

   For devcards 0.2.7, we have to make the following adjustment for making it
   work with shadow-cljs.

   #+begin_src clojure
          {:builds
           {:app
            {:build-options {:ns-aliases {devcards-marked cljsjs.marked
                                          devcards-syntax-highlighter cljsjs.highlight}}}}}

     (ns cljsjs.marked
       (:require ["marked" :as marked]))

     (js/goog.exportSymbol "marked" marked)
     (js/goog.exportSymbol "DevcardsMarked" marked)

     (ns cljsjs.highlight
       (:require ["highlight" :as highlight]))

     (js/goog.exportSymbol "highlight" highlight)
     (js/goog.exportSymbol "DevcardsSyntaxHighlighter" highlight)

   #+end_src

*** Sources
    https://clojureverse.org/t/introducing-shadow-cljs-inspect/5012

** Links

   - [[https://shadow-cljs.github.io/docs/UsersGuide.html][shadow-cljs]]
   - [[https://clojurescript.org/][cljs]]


** See also (generated)

   - [[id:9336fa0f-85f3-4943-b374-6ca2f01ee0f8][Clojure]]
   - [[id:2af1bd7c-d1a2-46e0-b820-f1d23090c2fc][Clojure Functional Programming Principles]]
   - [[id:0dffd466-49f4-46d0-ab62-4c0cca23b2af][Clojure toolkit]]
   - [[id:aea0aa1b-64be-44f9-a9f5-cc3e215d9d4c][Datascript]]
   - [[id:87c93bc1-a6ef-47e3-b81e-dc7ba09324a8][High Performance CLJS]]
   - [[id:bca207fc-25d3-45ff-a05f-8da06210c660][Life In Dynamic Typing]]
   - [[id:187c080d-b3ef-4f46-8ba9-2a62fbbb9876][Web App Testing]]
