:PROPERTIES:
:ID:       8c632bb6-d0b3-410f-b184-cde6d851aadd
:ROAM_ALIASES: kubernete k8s docker
:END:
#+TITLE: Devops
#+OPTIONS: toc:nil
#+filetags: :docker:kubernete:

* Docker and Kubernete
  Docker are containers/processes which can be considered as lightweight VMs.
  Kuberenetes (K8s) are container orchestration. They allow for load balancing
  (2 level with ingress (external load balancing) and service (internal load
  balancer)) on pods (docker containers). They allow for recover from failure
  for resource, and rolling update.

  Podman, with podman-compose and buildah are alternative to docker and
  docker-compose.

* DevOPS
  Learn about ansible (again).


** Ubuntu Server/Install Starting Projects
*** DONE Git [3/3]
    Remains to test in practice, but the [[https://github.com/davidpham87/new-ubuntu-config][project]] is pretty stable now.
    - [X] Create a python file that writes the makefile automatically
    - [X] Create README.md where appropriate.
    - [X] Test the application

* Java and Graal

  Alternative to select which version of java is used.
  https://gist.github.com/ricardozanini/fa65e485251913e1467837b1c5a8ed28

** See also (generated)

   - [[id:555e395a-17db-430e-b416-1329d2039882][Multipass]]

