:PROPERTIES:
:ID: bd688479-4931-4006-b35f-c943ae7dfcc7
:ROAM_ALIASES: Problem Solving
:END:
#+TITLE: Problem Solving
#+OPTIONS: toc:nil
#+DATE: 2022-01-03
#+filetags: :problem-solving:scientific-method:skepticism

- [[id:1eec7b94-0959-400a-87a6-11161a0464d7][How to Solve it]] from Polya.
- [[id:f65785b4-b6c7-48bf-b53f-046512a74952][Design, Composition and Performance]] from Rich Hickey.
- [[id:554d2f50-b05a-4776-a593-361ffb5e1226][Scientific Method: Skepticism]] (multiple authors).

* How to Solve it

  Basically, it is a receipe on how to solve logical problems (what is the
  data, what are the constrains, what is the question)

* Design, Composition and Performance

  It lays out the plan to build solutions when the problems are ambiguous and
  will evolve in a dynamic world.

* Scientific Method and Skepticism

  How do we know that what we know is true? We should ask ourselves how we know
  things and where mistakes and bias might occur. This is this part is
  important. Human are full of biases (perception and memory) and might also
  employ fallacies to argue (such as the appeal to authority, to nature or to
  perfect solution).
